services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  yyy-api:
    container_name: yyy-api
    image: yxqnyyy/yyy-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  yyy-react:
    container_name: yyy-react
    image: yxqnyyy/yyy-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - yyy-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
