aws:
  s3:
    mock: false
spring:
  datasource:
    url: jdbc:postgresql://awseb-e-kgrhnwtyva-stack-awsebrdsdatabase-zrpo2k7j9ata.c4neaifzgnuq.eu-central-1.rds.amazonaws.com:5432/ebdb
    username: amigoscode
    password: password